
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
        app: todoapp
    spec:
      containers:
        - image: terezabisharyan/app-backend:62303f82776d6dc6222071375b1dd9a15d1d015e
          imagePullPolicy: Always
          name: myweb
          ports:
            - containerPort: 3001
          env:
            - name: "DBHOST"
              value: headless
