
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
        app: todoapp
    spec:
      containers:
        - image: terezabisharyan/app-backend:244e7b218b4fa160135f4ad67b4747d5ebf665b8
          imagePullPolicy: Always
          name: myweb
          ports:
            - containerPort: 3001
          env:
            - name: "DBHOST"
              value: mongo
