apiVersion: v1
kind: Service
metadata:
   name: node-service
   labels:
     app: node-service
      
spec:
   type: LoadBalancer
   ports:
     - protocol: TCP
       port: 3001
       targetPort: 3001
   selector:
     app: back-deploy
