apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - back-deploy.yaml
  - back-service.yaml
  - headless.yaml
  - mongo-sts.yaml
  - mongo-service.yaml
  - pers-volume.yaml
  - secret.yaml
