apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    name: web
    app: todoapp
spec:
  selector:
    name: web
  type: NodePort
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      nodePort: 30001
      protocol: TCP
